//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgDelivery
    {
        public int ImgDeliId { get; set; }
        public string DeliveryImg { get; set; }
        public byte SortDeli { get; set; }
        public Nullable<int> DeliveryId { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
