//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.ImgNews = new HashSet<ImgNew>();
        }
    
        public int NewsId { get; set; }
        public string NewTitles { get; set; }
        public string NewsDetails { get; set; }
        public string NewsBy { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public string EmployeeCode { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgNew> ImgNews { get; set; }
    }
}
