//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImgProducts = new HashSet<ImgProduct>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Promotion = new HashSet<Product_Promotion>();
        }

        public int ProductId { get; set; }

        [Display(Name = "Tên Sản Phẩm")]
        [Required(ErrorMessage = "Tên Sản Phẩm bắt buộc phải nhập")]
        public string ProductName { get; set; }

        [Display(Name = "Mô Tả Chi Tiết")]
        [Required(ErrorMessage = "Bạn chưa nhập mô tả cho sản phẩm này")]
        public string ProductDetails { get; set; }

        [Display(Name = "Trạng Thái")]
        public Nullable<bool> ProductStatus { get; set; }

        public string ProductImg { get; set; }

        [Display(Name = "Ngày Cập Nhật")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Vui lòng chọn ngày cập nhật")]
        public Nullable<System.DateTime> ProductUpdate { get; set; }

        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "Bạn phải nhập số lượng cho sản phẩm")]
        public Nullable<int> ProductQty { get; set; }

        [Display(Name = "Giá Bán")]
        [Required(ErrorMessage = "Vui lòng nhập giá cho sản phầm")]
        [DataType(DataType.Currency, ErrorMessage = "Bạn phải nhập vào giá tiền")]
        public Nullable<decimal> ProductSold { get; set; }

        [Display(Name = "Giá Cũ")]
        [Required(ErrorMessage = "Hãy nhập giá cũ cho sản phẩm này")]
        [DataType(DataType.Currency, ErrorMessage = "Bạn phải nhập vào giá tiền")]
        public Nullable<decimal> ProductsOldPrice { get; set; }

        public Nullable<int> SupplierId { get; set; }

        public Nullable<int> CategoryId { get; set; }

    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgProduct> ImgProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Promotion> Product_Promotion { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
