//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.Product_Promotion = new HashSet<Product_Promotion>();
        }
    
        public int PromotionId { get; set; }
        public string PromotionName { get; set; }
        public string PromotionDetails { get; set; }
        public Nullable<int> PromotionDiscount { get; set; }
        public Nullable<bool> PromotionStatus { get; set; }
        public Nullable<System.DateTime> PromotionOpen { get; set; }
        public Nullable<System.DateTime> PromotionClose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Promotion> Product_Promotion { get; set; }
    }
}
